import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'de' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isSearchOpen: boolean;
  setIsSearchOpen: (open: boolean) => void;
}

const translations: Record<Language, Record<string, string>> = {
  de: {
    // Navigation
    'nav.validator': 'Validator',
    'nav.generator': 'Generator',
    'nav.bulk': 'Bulk-Scan',
    'nav.badge': 'Trust-Badge',
    'nav.api': 'API Docs',
    'nav.legal': 'Recht & Steuern',
    'nav.matrix': 'Matrix',
    'nav.doh_test': 'DNS prüfen',
    'nav.mobile_validate': 'DNS Prüfen',
    'nav.mobile_generate': 'Record Bauen',

    // Hero Section
    'hero.badge': 'IETF RFC 10023 • DNS-Knoten: _for-sale',
    'hero.title_part1': 'Kein Parking.',
    'hero.title_part2': 'Keine Weiterleitung.',
    'hero.title_part3': 'Verkaufen direkt im DNS.',
    'hero.desc': 'Der Standard RFC 10023 definiert, wie Domainverkäufe direkt im Domain Name System hinterlegt werden. Statt Besucher auf Werbeseiten umzuleiten, tragen Inhaber Preis und Kontakt in einen TXT-Eintrag ein. Registrare und Kaufinteressenten lesen das Angebot automatisiert aus.',
    'hero.cta_validate': 'Domain live prüfen',
    'hero.cta_generate': 'Eintrag erstellen',
    'hero.cta_bulk': 'Bulk-Scan →',
    'hero.stat_commission': 'Provision',
    'hero.stat_record': 'Record-Typ',
    'hero.stat_mandatory': 'Pflichtfeld',

    // Terminal Hero Preview
    'hero.terminal_header': 'RFC 10023 Wire Protocol',
    'hero.terminal_comment': '# Abfrage der Verkaufsdaten einer Domain:',
    'hero.terminal_node': 'DNS-Knoten:',
    'hero.terminal_dnssec': 'DNSSEC:',
    'hero.terminal_dnssec_val': 'Signiert und authentifiziert',
    'hero.terminal_standard': 'Standard:',
    'hero.terminal_example': 'Praxisbeispiel: Registry SIDN (.nl)',
    'hero.terminal_spec_link': 'Spezifikation lesen →',

    // Feature Cards
    'feat.bulk_title': 'Portfolio Bulk-Scanner',
    'feat.bulk_desc': 'Bis zu 30 Domains parallel prüfen, DNSSEC abfragen und als CSV exportieren.',
    'feat.badge_title': 'Verifikations-Badge',
    'feat.badge_desc': 'Kopierbare Badges für Verkaufsseiten mit Direktlink zur Prüfung.',
    'feat.api_title': 'Öffentliche REST-API',
    'feat.api_desc': 'Kostenfreie Schnittstelle für Entwickler, Skripte und Abfrage-Tools.',
    'feat.legal_title': 'Recht und Steuern',
    'feat.legal_desc': 'Impressumspflicht nach § 5 DDG, Vertragsrecht und Preisangaben im DACH-Raum.',

    // Definition Box
    'def.badge': 'IETF Spezifikation',
    'def.text': 'RFC 10023 standardisiert die DNS-Signalisierung von Verkaufsangeboten über einen TXT-Resource-Record am Knotennamen _for-sale.[domain]. Das Protokoll ermöglicht Registraren, Resolvern und automatisierten Abfrage-Tools das strukturierte Auslesen von Verkaufsparametern (v=FORSALE1;), Preisforderungen (fval) und verifizierten Kontakt-URIs (furi) direkt aus der autoritativen Zone.',
    'def.spec_link': 'RFC 10023 Spezifikation →',

    // Bento / Comparison Grid
    'bento.bg_badge': 'Hintergrund',
    'bento.main_title': 'Warum DNS-Signale herkömmliches Parking ablösen',
    'bento.card1_badge': 'Ablauf',
    'bento.card1_title': 'Direkte Erkennung bei Whois- und Verfügbarkeitsprüfungen',
    'bento.card1_desc': 'Bisher sah ein Interessent erst beim Aufruf im Webbrowser, ob eine Domain zum Verkauf steht. RFC 10023 verlagert diese Information in das DNS:',
    'bento.step1': '1. Inhaber setzt TXT-Eintrag',
    'bento.step2': '2. Resolver liest v=FORSALE1 aus',
    'bento.step3': '3. Registrar zeigt Verkaufsoption',
    'bento.card1_footer': 'Keine Bindung an externe Parkingservices',
    'bento.card1_tech_link': 'Technische Details →',

    'bento.card2_badge': 'Vergleich',
    'bento.card2_title': 'Klassisches Parking versus RFC 10023',
    'bento.row_commission': 'Verkaufsprovision',
    'bento.row_commission_val': '0 % (beim Direktverkauf)',
    'bento.row_ns': 'Nameserver-Wechsel',
    'bento.row_ns_val': 'Nicht nötig',
    'bento.row_deindex': 'Deindexierungsrisiko',
    'bento.row_deindex_val': 'Keines',
    'bento.row_dnssec': 'DNSSEC-Signierung',
    'bento.row_dnssec_val': 'Voll unterstützt',
    'bento.row_machine': 'Maschinenlesbar',
    'bento.row_machine_val': 'Offizieller Standard',
    'bento.card2_note': '* Gilt für Direktverkäufe über den im DNS hinterlegten Kontaktlink.',

    'bento.card3_badge': 'Praxiseinsatz',
    'bento.card3_title': 'Registry SIDN (.nl) prüft RFC 10023 bei Domainabfragen',
    'bento.card3_desc': 'Die niederländische Vergabestelle SIDN fragt bei Verfügbarkeitsprüfungen automatisiert den Eintrag _for-sale ab. Steht eine .nl-Adresse zum Verkauf, erscheint der Hinweis samt Preis und Kontakt direkt im Suchergebnis.',
    'bento.card3_btn': 'SIDN.nl öffnen',

    // Quote
    'quote.text': '„RFC 10023 trennt das Verkaufsangebot von der eigentlichen Website. Eine Domain muss nicht brachliegen oder auf Werbebanner umgeleitet werden, um Kaufinteressenten zu signalisieren, dass Angebote willkommen sind.“',
    'quote.author': '— IETF DNSOP Working Group',

    // FAQs
    'faq.badge': 'Fragen und Antworten',
    'faq.title': 'Häufige Fragen zu RFC 10023',
    'faq.desc': 'Detaillierte Antworten auf die wichtigsten technischen, rechtlichen und praktischen Fragen zum IETF-Standard für Domain-Verkaufssignale im DNS.',
    'faq.view_all': 'Alle Fragen & Antworten im FAQ-Hub →',
    'faq.search_placeholder': 'FAQ durchsuchen...',
    'faq.cat_all': 'Alle Themen',
    'faq.cat_general': 'Allgemein & Funktion',
    'faq.cat_technical': 'Technik & DNSSEC',
    'faq.cat_legal': 'Recht & Steuern',
    'faq.cat_hoster': 'Hoster & Registrars',
    'faq.q1': 'Warum RFC 10023 statt klassischem Domainparking bei Sedo oder Afternic?',
    'faq.a1': 'Domainparking über externe Werbeseiten birgt handfeste Nachteile: Browser blockieren die Banner, Suchmaschinen strafen geparkte Adressen mit Deindexierung ab und bei einem Verkauf fallen 10 bis 15 Prozent Provision an. Mit RFC 10023 bleibt die Domain auf Ihren regulären Nameservern oder einer eigenen Webpräsenz erreichbar. Das Verkaufsangebot wird direkt im DNS signalisiert, lesbar für Registrare und Käufer ohne Zwischenhändler.',
    'faq.q2': 'Muss jede Tag-Angabe in einen separaten TXT-Eintrag?',
    'faq.a2': 'Nach RFC 10023 Abschnitt 2.1 lautet die Vorgabe der IETF: Jeder TXT-Eintrag enthält genau ein Tag-Wert-Paar (zum Beispiel Eintrag 1 mit "v=FORSALE1;fval=USD195000" und Eintrag 2 mit "v=FORSALE1;furi=https://..."). Unser Generator unterstützt sowohl dieses offizielle Verfahren als auch die einzeilige Variante für Nameserver mit einfacher Menüführung.',
    'faq.q3': 'Wie erkennen Registrare und Broker, dass eine Domain zum Verkauf steht?',
    'faq.a3': 'Registrare wie die niederländische Registry SIDN für .nl führen bei Verfügbarkeitsabfragen einen DNS-Query auf Typ 16 (TXT) am Knotennamen _for-sale durch. Findet das System den Eintrag "v=FORSALE1", zeigt der Registrar dem Interessenten direkt den Kaufpreis und den Kontakt an.',
    'faq.q4': 'Welche Kosten entstehen durch den DNS-Standard?',
    'faq.a4': 'Keine. RFC 10023 ist ein offener Standard der IETF. TXT-Einträge im DNS gehören bei praktisch allen Hostern zum kostenfreien Standardumfang einer Domain.',
    'faq.q5': 'Wie schützt man sich vor Spam auf die Kontaktdaten?',
    'faq.a5': 'Im Tag furi sollte man statt einer offenen Mailadresse besser einen Link zu einem geschützten Kontaktformular, einer Projektseite oder einem Treuhandkonto angeben. So bleibt die Domain maschinenlesbar, ohne Angriffsfläche für Adress-Sammler zu bieten.',
    'faq.q6': 'Was bedeutet das Pflichtfeld v=FORSALE1?',
    'faq.a6': 'v=FORSALE1 ist der standardisierte Protokoll- und Versionsbezeichner nach RFC 10023. Er muss zwingend am Anfang jedes RFC 10023 TXT-Eintrags stehen und mit einem Semikolon enden. Fehlt dieses Feld oder weicht der Name ab, verwerfen automatische Scanner und Registrare den Record.',
    'faq.q7': 'Welche Währungen und Preisformate werden in fval unterstützt?',
    'faq.a7': 'Das Preisfeld fval verlangt nach RFC 10023 zwingend den dreistelligen ISO 4217 Währungscode unmittelbar vor dem Betrag ohne Leerzeichen (z. B. EUR5000 oder USD12500). Nachkommastellen können mit einem Punkt angegeben werden (z. B. EUR2500.50). Verhandlungsbasis (VHB) wird durch das Weglassen des fval-Tags und einen Hinweis im Textfeld ftxt signalisiert.',
    'faq.q8': 'Wie verhält sich RFC 10023 zu DNSSEC?',
    'faq.a8': 'RFC 10023 harmoniert perfekt mit DNSSEC. Da _for-sale ein regulärer Knotenpunkt der DNS-Zone ist, wird der TXT-Record durch den zuständigen RRSIG-Eintrag kryptografisch signiert. Käufer und Registrare können so fälschungssicher verifizieren, dass das Verkaufsangebot tatsächlich vom Domaininhaber stammt (Schutz gegen DNS-Spoofing und Cache Poisoning).',
    'faq.q9': 'Welche Time-to-Live (TTL) sollte für den TXT-Eintrag gewählt werden?',
    'faq.a9': 'Wir empfehlen eine Standard-TTL von 3600 Sekunden (1 Stunde) oder 7200 Sekunden. Sollte sich der Preis ändern oder die Domain verkauft werden, propagiert die Deaktivierung des Verkaufsstatus zügig innerhalb von maximal ein bis zwei Stunden weltweit durch die Resolver-Caches.',
    'faq.q10': 'Ist ein DNS-Eintrag ein rechtlich bindendes Kaufangebot nach § 145 BGB?',
    'faq.a10': 'Nein. Im Zivilrecht gilt die Veröffentlichung eines Preises im DNS-Eintrag als unverbindliche Aufforderung zur Abgabe von Angeboten (invitatio ad offerendum). Als Domaininhaber behalten Sie die volle Vertragsfreiheit und können jedes Kaufangebot frei annehmen oder ablehnen.',
    'faq.q11': 'Gilt die Impressumspflicht nach § 5 DDG für den DNS-Eintrag?',
    'faq.a11': 'Ein reiner DNS TXT-Record ist kein Telemediendienst und benötigt kein eigenes Impressum. Wichtig ist jedoch, dass die im Tag furi verlinkte Kontaktseite ein vollständiges, leicht auffindbares Impressum sowie eine Datenschutzerklärung bereithält.',
    'faq.q12': 'Was tun, wenn mein Hoster Unterstriche im Zoneneditor verbietet?',
    'faq.a12': 'Einige wenige Hoster validieren DNS-Namen fälschlicherweise gegen alte Hostnamen-Regeln. In diesem Fall kann man die autoritativen Nameserver kostenfrei auf moderne DNS-Provider wie Cloudflare DNS, Hetzner DNS oder deSEC delegieren. Die eigentliche Domainregistrierung bleibt beim bisherigen Hoster.',
    'faq.q13': 'Gibt es eine Längenbegrenzung für den TXT-Record?',
    'faq.a13': 'Ja, nach RFC 1035 darf ein einzelner String innerhalb eines DNS-TXT-Records maximal 255 Bytes lang sein. Unser Generator überwacht diese Grenze in Echtzeit ("Byte-Guard"), sodass Ihre Einträge garantiert syntaktisch valide bleiben.',
    'faq.q14': 'Kann eine Domain gleichzeitig produktiv betrieben werden und zum Verkauf stehen?',
    'faq.a14': 'Ja! Das ist einer der größten Vorteile von RFC 10023. Ihre bestehende Website auf www oder der Apex-Domain läuft vollkommen ungestört weiter. Nur der spezielle Knoten _for-sale signalisiert Registraren und interessierten Käufern im Hintergrund, dass Angebote willkommen sind.',

    // Widget Embed
    'widget.title': 'Widget zum Einbinden',
    'widget.desc': 'Binde den RFC 10023 Validator oder Generator direkt in deine Website, dein Blog oder ein Kundenportal ein.',
    'widget.copy_btn': 'Code kopieren',
    'widget.copied': 'Kopiert!',

    // Validator Page standalone
    'valpage.badge': 'DNS-Prüfung',
    'valpage.title': 'RFC 10023 DNS-Validator',
    'valpage.desc': 'Prüfen Sie Domains weltweit in Echtzeit auf vorhandene _for-sale TXT-Einträge und deren Konformität mit dem IETF-Standard.',
    'valpage.diag_title': 'Wie funktioniert die Prüfung?',
    'valpage.diag_text': 'Die Abfrage läuft direkt aus Ihrem Browser an öffentliche Anycast-Resolver von Cloudflare und Google. Dabei wird der TXT-Eintrag am Namen _for-sale.[domain] abgefragt. Das Skript prüft anschließend den Versionsheader v=FORSALE1; und die Felder fval, furi sowie ftxt.',

    // Generator Page standalone
    'genpage.badge': 'Generator',
    'genpage.title': 'RFC 10023 Generator',
    'genpage.desc': 'Erstellen Sie standardkonforme DNS-TXT-Einträge für Ihre Domains und exportieren Sie den fertigen Code für Cloudflare, BIND, Hetzner, INWX oder die Kommandozeile.',
    'genpage.guide_title': 'So hinterlegen Sie den Eintrag',
    'genpage.step1_title': '1. DNS öffnen',
    'genpage.step1_desc': 'Melden Sie sich bei Ihrem Registrar oder DNS-Anbieter an und öffnen Sie die DNS-Verwaltung der Domain.',
    'genpage.step2_title': '2. Typ und Name wählen',
    'genpage.step2_desc': 'Wählen Sie als Typ TXT und tragen Sie als Name _for-sale ein.',
    'genpage.step3_title': '3. Prüfen',
    'genpage.step3_desc': 'Fügen Sie den generierten Text als Wert ein. Nach wenigen Minuten können Sie den Eintrag mit unserem Prüftool testen.',

    // Validator Component
    'val.badge': 'Live DNS-Abfrage mit Hostprüfung',
    'val.title': 'RFC 10023 Prüftool',
    'val.node_prefix': 'Knoten: _for-sale.[domain]',
    'val.placeholder': 'beispieldomain.de',
    'val.invalid_domain': 'Bitte geben Sie einen gültigen Domainnamen ein (zum Beispiel forsaledns.net oder beispieldomain.de).',
    'val.btn_check': 'Prüfen',
    'val.btn_checking': 'Prüfe...',
    'val.examples': 'Beispiele:',
    'val.dig_btn': 'dig Befehl',
    'val.dig_copied': 'dig kopiert!',
    'val.dig_title': 'Kopiert den passenden Terminal-Befehl',
    'val.esc_hint': '[Esc zum Leeren]',
    'val.copy_record': 'Eintrag kopieren',
    'val.record_copied': 'Kopiert!',
    'val.dnssec_confirmed': 'DNSSEC bestätigt',
    'val.detected_hoster': 'Erkannter Nameserver',
    'val.create_for_hoster': 'Eintrag für diesen Hoster erstellen',
    'val.architecture_label': 'Aufbau:',
    'val.price_label': 'Preis',
    'val.price_empty': 'Nicht hinterlegt',
    'val.contact_label': 'Kontaktadresse',
    'val.contact_empty': 'Keine Adresse hinterlegt',
    'val.note_label': 'Notiz',
    'val.warnings_title': 'Hinweise zum Eintrag:',
    'val.raw_show': '[+] Raw TXT anzeigen',
    'val.raw_hide': '[-] Raw TXT verbergen',
    'val.raw_title': 'Unformatierte DNS TXT Antworten',
    'val.inspector_show': '[+] DNS-Inspektor',
    'val.inspector_hide': '[-] DNS-Inspektor ausblenden',
    'val.dnssec_valid': 'true (validiert)',
    'val.dnssec_unsigned': 'false (unsigniert)',
    'val.seconds': 'Sekunden',
    'val.share_title': 'Prüfergebnis für',
    'val.share_end': 'teilen:',
    'val.audit_title': 'Domain-Audit & E-Mail-Sicherheit',
    'val.audit_badge': 'Multi-Vektor DNS Prüfung',
    'val.audit_score_label': 'Readiness Index',
    'val.audit_copy_json': 'JSON kopieren',
    'val.audit_json_copied': 'JSON kopiert!',
    'val.audit_share_link': 'Link kopieren',
    'val.audit_link_copied': 'Link kopiert!',
    'val.audit_email_hygiene': 'E-Mail & Routing-Schutz',
    'val.audit_tab_all': 'Alle Prüfungen',

    // Search Component
    'search.button_label': 'Suchen',
    'search.shortcut': '⌘K',
    'search.placeholder': 'Suche nach Tools, Tags (fval, furi), Hostern...',

    // Generator Component
    'gen.badge': 'DNS-Eintrag erstellen',
    'gen.title': 'RFC 10023 Generator',
    'gen.rfc_conform': 'RFC 10023 konform',
    'gen.step1': '1. Domainname',
    'gen.step2': '2. Preisvorstellung (fval)',
    'gen.vhb': 'Verhandlungsbasis (VHB)',
    'gen.step3': '3. Kontaktadresse oder Link (furi)',
    'gen.step3_hint': 'Empfehlung: Link zu einem Treuhanddienst (z. B. Escrow.com), Sedo, Afternic oder einem geschützten Kontaktformular.',
    'gen.step4': '4. Notiz oder Zusatz (ftxt)',
    'gen.format': 'Format:',
    'gen.format_multi': 'Multi-Record RRset (IETF RFC 10023 Standard)',
    'gen.format_single': 'Single-Line (Workaround)',
    'gen.format_single_warn': 'Hinweis: Nach RFC 10023 Abschnitt 2.1 darf jeder TXT-Record nur genau ein Tag-Wert-Paar enthalten (MUST NOT). Verwenden Sie diesen einzeiligen Modus nur als Notlösung, falls Ihr Hoster-Panel keine multiplen TXT-Einträge unter demselben Knotennamen zulässt.',
    'gen.copy_code': 'Code kopieren',
    'gen.copied': 'Kopiert!',
    'gen.share_link': 'Link teilen',
    'gen.node_label': 'Knoten: _for-sale.',
    'gen.vhb_note': 'Standard-Logik: Bei VHB wird kein fval-Feld gesetzt, sondern der Hinweis landet im Textfeld ftxt.',
    'gen.default_domain': 'beispieldomain.de',
    'gen.default_ftxt': 'Inkl. Treuhandservice, Sofortübertrag',
    'gen.vhb_tag': 'Verhandlungsbasis (VHB)',
    'gen.furi_placeholder': 'https://escrow.com/... oder https://ihre-seite.de/kontakt',
    'gen.ftxt_placeholder': 'Inklusive Treuhandabwicklung und Rechnung',
    'gen.size_label': 'Größe:',
    'gen.size_rfc': 'Bytes (RFC 1035 konform)',
    'gen.share_label': 'Prüflink:',
    'gen.tab_zonefile': 'Zonefile',
    'gen.tab_cf': 'Cloudflare',
    'gen.tab_hetzner': 'Hetzner',
    'gen.tab_inwx': 'INWX',
    'gen.tab_tf': 'Terraform',
    'gen.tab_dnscontrol': 'DNSControl',
    'gen.tab_cli': 'dig / curl',
    'gen.byte_warn_title': 'Achtung: String zu lang',
    'gen.byte_warn_text': 'Ein einzelner DNS-TXT-String darf höchstens 255 Bytes lang sein. Bitte kürzen Sie den Text (ftxt) oder die Webadresse (furi).',
    'gen.comment_bind_zone': '; DNS-Einträge für Zonefile:',
    'gen.comment_bind_node': '; Knoten: _for-sale.',
    'gen.comment_bind_type': '(Typ TXT, IN-Klasse)',
    'gen.comment_cf_dash': '# Cloudflare DNS Dashboard (Einträge einzeln anlegen):',
    'gen.comment_cf_hint': '# Hinweis: Den Inhalt im Dashboard ohne Anführungszeichen einfügen.',
    'gen.entry_label': 'Eintrag',
    'gen.type_label': 'Typ',
    'gen.name_label': 'Name',
    'gen.content_label': 'Inhalt',
    'gen.value_label': 'Wert',
    'gen.comment_hetzner_dash': '# Hetzner DNS Console (dns.hetzner.com):',
    'gen.comment_hetzner_hint': '# Name jeweils als \'_for-sale\' eintragen:',
    'gen.comment_inwx_dash': '# INWX oder Netcup DNS-Verwaltung:',
    'gen.comment_tf_def': '# Terraform Definition (Cloudflare Provider)',
    'gen.comment_cli_dig': '# 1. Lokale Abfrage mit dig:',
    'gen.comment_cli_doh': '# 2. Abfrage über DNS over HTTPS (Cloudflare):',
    'gen.comment_cli_api': '# 3. Direkte Abfrage über rfc10023.de API:',

    // E-E-A-T Trust Box
    'trust.badge': 'E-E-A-T Fachredaktion & Datenquellen',
    'trust.title': 'Redaktionelle Qualitätsgarantie & Primärquellen',
    'trust.reviewed_by': 'Fachredaktion rfc10023.de · Stand: September 2026',
    'trust.standards_label': 'Geprüft nach Standards:',
    'trust.standards_val': 'IETF RFC 10023 · RFC 1035 · RFC 8552 · W3C DoH (RFC 8484)',
    'trust.sources_label': 'Offizielle Primärquellen:',
    'trust.sources_val': 'IETF Datatracker, RFC Editor, SIDN (nl), DENIC eG, Cloudflare & Google Public DNS.',
    'trust.methodology': 'Methodik & Transparenz: Sämtliche Validierungen erfolgen in Echtzeit ohne Zwischenspeicherung via DNS over HTTPS (DoH) direkt auf autoritativen Anycast-Resolvern. Alle Code-Exporte entsprechen den strengen Wire-Format-Grenzen (max. 255 Bytes je String nach RFC 1035).',

    // Footer Links
    'footer.claim': 'Das unabhängige DACH-Referenzportal und Entwickler-Toolkit zum IETF-Standard RFC 10023. Dezentrale, standardisierte Kennzeichnung von Domain-Verkaufsabsichten ohne proprietäre Plattform-Abhängigkeit.',
    'footer.disclaimer_title': 'Unabhängigkeitshinweis:',
    'footer.disclaimer': 'rfc10023.de ist ein freies Fach- und Informationsportal. Es besteht kein gesellschaftsrechtliches Verhältnis zur Internet Engineering Task Force (IETF) oder DENIC eG.',
    'footer.tools_title': 'Tools & Hub',
    'footer.link_validator': 'Live DNS-Validator',
    'footer.link_generator': 'Record Builder & Byte-Guard',
    'footer.link_bulk': 'Portfolio Bulk-Scanner',
    'footer.link_badge': 'Trust-Badge Generator',
    'footer.link_api': 'Öffentliche REST-API',
    'footer.link_matrix': 'Hoster-Kompatibilität',
    'footer.standards_title': 'Recht & Standards',
    'footer.link_legal': 'Rechtssicherheit & Steuern',
    'footer.link_spec': 'IETF Spezifikations-Guide',
    'footer.link_faq': 'Häufige Fragen (FAQ)',
    'footer.link_orig_rfc': 'IETF RFC 10023 Original',
    'footer.link_imprint': '→ Impressum (§ 5 DDG)',
    'footer.link_privacy': 'Datenschutzerklärung (DSGVO)',
    'footer.share_label': 'Fachportal weiterempfehlen:',
    'footer.status_info': 'IETF RFC 10023 · Status: Informational · Stand: Sept. 2026',
    'footer.gdpr': '100 % DSGVO-konform',
    'footer.analytics': 'Cookielose Vercel Analytics',
    'footer.imprint_bottom': 'Impressum',

    // Matrix Page & HosterMatrix
    'matrix.badge': 'DACH Provider Evaluation',
    'matrix.title': 'Hoster- & DNS-Kompatibilitäts-Matrix',
    'matrix.desc': 'Welcher Hoster unterstützt die Eingabe von Underscore-Labels wie _for-sale im Webinterface? Detaillierte Testergebnisse für Hetzner, Cloudflare, INWX, Netcup, Strato und IONOS.',
    'matrix.subbadge': 'Kompatibilitäts-Matrix DACH',
    'matrix.subtitle': 'DNS-Zoneneditoren & Hoster im RFC 10023 Test',
    'matrix.search_placeholder': 'Hoster suchen...',
    'matrix.filter_all': 'Alle Status',
    'matrix.filter_supported': '🟢 Voll unterstützt',
    'matrix.filter_partial': '🟡 Eingeschränkt',
    'matrix.col_provider': 'Anbieter / Dienst',
    'matrix.col_origin': 'Herkunft',
    'matrix.col_status': 'RFC 10023 Status',
    'matrix.col_syntax': 'Zoneneditor-Syntax',
    'matrix.col_notes': 'Praxis-Hinweise & Workaround',
    'matrix.status_supported': 'Voll unterstützt',
    'matrix.status_partial': 'Eingeschränkt',
    'matrix.tech_bg_title': 'Technischer Hintergrund: Warum lehnen manche Hoster Unterstriche ab?',
    'matrix.tech_bg_text': 'Historisch verlangt der Standard für Hostnamen (RFC 1035 / RFC 1123) das Format [a-z0-9-]. Das Domain Name System als Protokoll erlaubt jedoch nach RFC 2181 beliebige Oktette. Für Service-Records und globale Attribute definierte die IETF in RFC 8552 den Standard für sogenannte Underscored Leaf Nodes (wie _dmarc, _domainkey oder nun _for-sale). Moderne DNS-Provider unterstützen diesen Standard uneingeschränkt; ältere Kontrollpanels prüfen Eingaben jedoch fälschlicherweise noch gegen die strikte Hostnamen-Syntax.',
    'matrix.rec_title': 'Empfohlene DNS-Provider',
    'matrix.rec_text': 'Wer viele Domains verwaltet und RFC 10023 flexibel einsetzen möchte, sollte auf Provider mit moderner DNS-Architektur setzen: Cloudflare DNS, Hetzner DNS Console, INWX oder deSEC. Hier können Einträge ohne Fehlermeldungen angelegt und sekundenschnell weltweit propagiert werden.',
    'matrix.workaround_title': 'Workaround für restriktive Hoster',
    'matrix.workaround_text': 'Verweigert das Webinterface deines Hosters (z. B. bei älteren Strato- oder IONOS-Tarifen) die Speicherung mit dem Hinweis auf ein ungültiges Zeichen im Hostnamen, kannst du die Nameserver der Domain kostenfrei auf Cloudflare oder deSEC delegieren. Die Domainregistrierung bleibt beim bisherigen Hoster erhalten.',
    'matrix.citation_title': 'Hoster- & DNS-Kompatibilitäts-Matrix für RFC 10023',

    // Bulk Page & BulkValidator
    'bulk.badge': 'Portfolio Werkzeug',
    'bulk.title': 'Portfolio Bulk-Scanner für RFC 10023',
    'bulk.desc': 'Prüfen Sie bis zu 30 Domains gleichzeitig auf vorhandene _for-sale Einträge, DNSSEC-Absicherung und die zuständigen Nameserver. Praktisch für Domaininhaber, Registrare und Makler.',
    'bulk.subbadge': 'Multi-Domain Portfolio Auditor',
    'bulk.limit_badge': 'Bis zu 30 Domains parallel',
    'bulk.label_input': 'Domains einfügen (Eine Domain pro Zeile):',
    'bulk.placeholder': 'domain1.de\ndomain2.at\ndomain3.ch',
    'bulk.btn_start': 'Bulk-Scan starten',
    'bulk.btn_scanning': 'Prüfe Portfolio',
    'bulk.btn_export': 'Ergebnisse als CSV exportieren',
    'bulk.col_domain': 'Domain',
    'bulk.col_status': 'Status',
    'bulk.col_price': 'Preis (fval)',
    'bulk.col_contact': 'Kontakt (furi)',
    'bulk.col_hoster': 'Hoster',
    'bulk.col_dnssec': 'DNSSEC',
    'bulk.status_valid': 'Valide',
    'bulk.status_syntax': 'Syntax',
    'bulk.status_not_found': 'Kein Record',
    'bulk.status_pending': 'Abfrage...',
    'bulk.status_error': 'Fehler',
    'bulk.dnssec_yes': 'JA',
    'bulk.dnssec_no': 'Nein',
    'bulk.privacy_title': 'Hinweise zu Ablauf und Datenschutz:',
    'bulk.privacy_text1': 'Die Abfrage läuft direkt in Ihrem Browser über DNS über HTTPS (DoH). Wir speichern keine der eingegebenen Domainlisten auf unseren Servern.',
    'bulk.privacy_legal': 'Rechtlicher Hinweis: Die Auswertung dient reinen Informationszwecken. Ein gefundener DNS-Eintrag begründet keinen Kaufvertrag nach § 145 BGB, sondern signalisiert lediglich die Verkaufsbereitschaft des Inhabers.',

    // Badge Page & BadgeGenerator
    'badge.badge': 'Verifikation für Domains',
    'badge.title': 'Badge Generator für RFC 10023',
    'badge.desc': 'Schaffen Sie Vertrauen bei Kaufinteressenten: Binden Sie ein verifizierbares Badge auf Ihrer Projektseite oder in Portfolios ein. Interessenten können den DNS-Eintrag mit einem Klick unabhängig nachprüfen.',
    'badge.subbadge': 'Prüfsiegel für Websites und Portfolios',
    'badge.verified_pill': '✓ DNS geprüft',
    'badge.domain_label': 'Domainname',
    'badge.theme_label': 'Farbvariante',
    'badge.theme_dark': 'Dunkel (Slate)',
    'badge.theme_emerald': 'Grün (Emerald)',
    'badge.theme_light': 'Hell (Weiß)',
    'badge.show_price': 'Preis zeigen',
    'badge.show_price_box': 'Preis im Badge',
    'badge.price_label': 'Preis oder Notiz',
    'badge.preview_label': 'Vorschau (Klickbar zur Prüfung):',
    'badge.preview_text': 'Interessenten gelangen per Klick direkt zum Prüfergebnis auf rfc10023.de, das den DNS-Eintrag unabhängig bestätigt.',
    'badge.code_web_title': 'Code für eigene Websites und Portale',
    'badge.code_md_title': 'Markdown für GitHub oder Readme',
    'badge.copy_html': 'HTML kopieren',
    'badge.copy_md': 'Markdown kopieren',
    'badge.benefit1_title': 'Echtheitsnachweis',
    'badge.benefit1_desc': 'Interessenten sehen sofort, dass das Angebot direkt aus der maßgeblichen DNS-Zone des Inhabers stammt.',
    'badge.benefit2_title': 'Provision sparen',
    'badge.benefit2_desc': 'Verlinken Sie direkt auf Ihr eigenes Kontaktformular oder einen Treuhanddienst wie Escrow.com und sparen Sie Vermittlungsgebühren.',
    'badge.benefit3_title': 'Datenschutzfreundlich',
    'badge.benefit3_desc': 'Der Badge-Code kommt ohne externe Tracker oder Schriftarten aus. Reines HTML und CSS.',

    // API Docs Page
    'api.badge': 'REST-API Dokumentation',
    'api.title': 'Kostenfreie Schnittstelle für RFC 10023',
    'api.desc': 'Für Entwickler, Registrare und Skripte: Fragen Sie beliebige Domains über unsere DNS-Infrastruktur ab und erhalten Sie ein klares JSON-Objekt mit allen Tags, Nameservern und dem DNSSEC-Status.',
    'api.feature_cors': 'CORS aktiv',
    'api.feature_auth': 'Keine Registrierung',
    'api.feature_anycast': 'Anycast DNS',
    'api.params_title': 'Parameter der Abfrage',
    'api.col_param': 'Parameter',
    'api.col_type': 'Typ',
    'api.col_required': 'Pflicht',
    'api.col_desc': 'Beschreibung',
    'api.param_or': 'oder',
    'api.param_yes': 'Ja',
    'api.param_desc': 'Der zu prüfende Domainname (zum Beispiel beispieldomain.de).',
    'api.console_title': 'Direkt im Browser ausprobieren',
    'api.btn_send': 'Abfrage senden',
    'api.btn_loading': 'Lade Daten...',
    'api.btn_copy_curl': 'cURL kopieren',
    'api.response_label': '// Server-Antwort (JSON):',
    'api.example_js': 'Beispiel in JavaScript / TypeScript',
    'api.example_py': 'Beispiel in Python',

    // Legal Guide Page
    'legal.badge': 'Rechtlicher Rahmen • DACH',
    'legal.title': 'Rechtliche Hinweise zu Domainverkäufen über DNS (RFC 10023)',
    'legal.desc': 'Was Domaininhaber und Unternehmen in Deutschland, Österreich und der Schweiz beachten sollten, wenn sie Verkaufsabsichten und Preisvorstellungen über DNS-Einträge signalisieren. Hinweise zu Impressumspflicht, BGB-Vertragsrecht, Steuern und Wettbewerbsrecht.',
    'legal.disclaimer_title': 'Wichtiger Hinweis:',
    'legal.disclaimer_text': 'Diese Übersicht dient reinen Informationszwecken und spiegelt den technischen und rechtlichen Stand wider. Sie stellt keine Rechtsberatung oder steuerliche Beratung dar und ersetzt nicht das Gespräch mit einem Fachanwalt für IT-Recht oder Steuerberater.',
    'legal.c1_title': 'Ist ein DNS-Eintrag ein verbindliches Kaufangebot (§ 145 BGB)?',
    'legal.c1_text1': 'Nach deutschem und europäischem Zivilrecht ist die Veröffentlichung eines Preises im DNS-Eintrag (wie fval=EUR2500) kein verbindliches Angebot an die Allgemeinheit, sondern eine unverbindliche Aufforderung zur Abgabe von Angeboten (Fachbegriff: invitatio ad offerendum).',
    'legal.c1_box_title': 'Bedeutung in der Praxis:',
    'legal.c1_box_text': 'Niemand kann durch eine einfache Annahmeerklärung einen Kauf erzwingen. Als Domaininhaber behalten Sie die volle Vertragsfreiheit und entscheiden frei, an wen und zu welchem Preis Sie die Domain verkaufen.',
    'legal.c2_title': 'Gilt die Impressumspflicht (§ 5 DDG) für den DNS-Eintrag?',
    'legal.c2_text1': 'Ein TXT-Eintrag im DNS ist kein Telemediendienst, der ein eigenes Impressum tragen muss. Aufgrund der technischen Längenbegrenzung von DNS-Strings wäre das auch gar nicht möglich.',
    'legal.c2_box_title': 'Empfehlung für das Feld furi:',
    'legal.c2_box_text': 'Verlinken Sie im Feld furi auf eine gesicherte Website, eine eigene Projektseite oder einen Treuhandservice, wo ein vollständiges, leicht auffindbares Impressum und eine Datenschutzerklärung hinterlegt sind. So vermeiden Sie Risiken nach dem Gesetz gegen den unlauteren Wettbewerb.',
    'legal.c3_title': 'Mehrwertsteuer und Preisangabenverordnung',
    'legal.c3_text1': 'Richtet sich ein Verkaufsangebot an Verbraucher, verlangt die Preisangabenverordnung in Deutschland grundsätzlich die Nennung von Endpreisen inklusive Umsatzsteuer.',
    'legal.c3_b2b': 'Im B2B-Bereich: Bei Verkäufen zwischen Unternehmern sind Nettopreise üblich.',
    'legal.c3_rec': 'Empfehlung für RFC 10023: Nutzen Sie das Freitextfeld ftxt für Klarheit, zum Beispiel mit dem Zusatz ftxt=Netto zzgl. USt. / B2B Transaktion oder ftxt=Endpreis inkl. MwSt..',
    'legal.c4_title': 'Markenschutz und Markenrechte',
    'legal.c4_text1': 'Ein öffentlicher Verkaufsvermerk im DNS dokumentiert die Absicht, eine Domain gegen Geld abzugeben. Verletzt die Domain fremde Markenrechte oder Firmennamen, kann ein hoher Kaufpreis von Gerichten oder Schiedsstellen als Indiz für Bösgläubigkeit gewertet werden.',
    'legal.c4_box': 'Wichtig: Nutzen Sie RFC 10023 nur für Domains, an denen Sie berechtigte Interessen halten und keine Rechte Dritter verletzen.',
    'legal.cta_title': 'Standardkonformen Eintrag erstellen',
    'legal.cta_desc': 'Nutzen Sie unseren Generator mit automatischer Längenprüfung und flexiblen Exportformaten.',
    'legal.cta_btn': 'Zum Generator →',

    // Specification Page
    'spec.badge': 'IETF RFC 10023 · Status: Informational',
    'spec.title': 'RFC 10023 Spezifikation',
    'spec.desc': 'Technische Analyse und deutsche Referenz des IETF-Standards „The \'_for-sale\' Underscored and Globally Scoped DNS Node Name“ (Juli 2026).',
    'spec.cat': 'Kategorie: Informational',
    'spec.orig_link': 'IETF Originaltext',
    'spec.s1_title': '1. Motivation und Discovery-Architektur',
    'spec.s1_text1': 'Im heutigen Domain-Sekundärmarkt ist die Erkennung zum Verkauf stehender Domains fragmentiert. Interessenten müssen die Domain im Browser aufrufen (in der Hoffnung, dass eine Parking-Seite geschaltet ist), Whois-Datenbanken prüfen (die durch Datenschutzgesetze wie die DSGVO meist redigiert sind) oder geschlossene Marktplatz-Verzeichnisse durchforsten.',
    'spec.s1_text2': 'RFC 10023 etabliert eine dezentrale, protokollbasierte Discovery-Schicht direkt im Domain Name System. Domaininhaber müssen ihre Nameserver nicht ändern und keine teuren Parkingservices nutzen: Ein einfacher DNS-TXT-Record signalisiert der weltweiten Internet-Infrastruktur, dass die Domain für Kaufangebote bereitsteht.',
    'spec.s2_title': '2. Der reservierte DNS-Knotenpunkt (_for-sale)',
    'spec.s2_text': 'Gemäß den Vorgaben von RFC 8552 (Scoped, Underscored DNS Node Names) nutzt die Spezifikation das Präfix _for-sale. Der Unterstrich verhindert Kollisionen mit gewöhnlichen Hostnamen (wie mail.example.de oder www.example.de), die nach RFC 1035 keine Unterstriche enthalten dürfen.',
    'spec.s2_comment': '; Syntax nach RFC 10023 Section 2.1 (Multi-Record RRset):',
    'spec.s3_title': '3. Tag-Value-Spezifikation (Section 2.1 & 2.2)',
    'spec.s3_text': 'Nach RFC 10023 Section 2.1 gilt: Jeder TXT-Record darf genau ein Tag-Wert-Paar enthalten und muss mit v=FORSALE1; beginnen. Mehrere Tags werden durch mehrere TXT-Records innerhalb desselben Resource Record Sets (RRset) abgebildet.',
    'spec.th_tag': 'Tag',
    'spec.th_required': 'Pflicht',
    'spec.th_meaning': 'Bedeutung',
    'spec.th_example': 'Beispielwert',
    'spec.tag_v_desc': 'Versionskennung. Muss exakt FORSALE1 lauten.',
    'spec.tag_fval_desc': 'Festpreis nach ISO 4217 (Code direkt vor dem Betrag). Bei VHB entfällt der Tag.',
    'spec.tag_furi_desc': 'Kontakt-URI (HTTP, HTTPS, mailto oder tel nach RFC 3986).',
    'spec.tag_ftxt_desc': 'Menschlich lesbare Notiz (z. B. Verhandlungsbasis, Konditionen).',
    'spec.tag_fcod_desc': 'Maschineller Transaktions- oder Identifikationscode.',
    'spec.s4_title': '4. Praxis-Implementierung: Die SIDN-Fallstudie (.nl)',
    'spec.s4_text': 'Die niederländische Länderregistry SIDN (.nl) hat RFC 10023 als weltweit erste Top-Level-Domain direkt in ihre Infrastruktur integriert. Führt ein Nutzer auf der offiziellen SIDN-Website oder per Whois-Lookup eine Domainabfrage durch, prüft das SIDN-Backend automatisch den _for-sale TXT-Record. Ist der Record vorhanden, erscheint in der Auskunft nicht „Domain vergeben“, sondern ein direkter Hinweis auf die Verkaufsbereitschaft inklusive Kaufpreis und Verkäuferkontakt.',
    'spec.s5_title': 'Sicherheitshinweise (Section 4 des RFC)',
    'spec.s5_text': 'RFC 10023 beinhaltet keine Authentifizierungsschicht für die Zahlungsabwicklung. Interessenten sollten vor Überweisungen sicherstellen, dass die Domain per DNSSEC signiert ist, um DNS-Cache-Poisoning auszuschließen. Zudem wird dringend empfohlen, Transaktionen stets über lizenzierte Treuhanddienste abzuwickeln.',
    'spec.citation_title': 'IETF RFC 10023: The _for-sale Underscored DNS Node Name',

    // Citation Box
    'citation.title': 'Zitierhinweis für Fachmedien & Publikationen',
    'citation.default_title': 'RFC 10023: Der IETF-Standard für Domain-Verkaufssignale im DNS',
    'citation.val_title': 'RFC 10023 DNS Live-Validator & Inspektor',
    'citation.gen_title': 'RFC 10023 Record Generator & Multi-Format Exporter',
    'citation.copy': 'Zitierung kopieren',
    'citation.copied': 'Zitierung kopiert',
    'citation.status': 'Stand: September 2026 · IETF Standards Track',
  },
  en: {
    // Navigation
    'nav.validator': 'Validator',
    'nav.generator': 'Generator',
    'nav.bulk': 'Bulk Scan',
    'nav.badge': 'Trust Badge',
    'nav.api': 'API Docs',
    'nav.legal': 'Legal & Taxes',
    'nav.matrix': 'DNS Providers',
    'nav.doh_test': 'Check DNS',
    'nav.mobile_validate': 'Check DNS',
    'nav.mobile_generate': 'Create Record',

    // Hero Section
    'hero.badge': 'IETF RFC 10023 • DNS Node: _for-sale',
    'hero.title_part1': 'No Parking.',
    'hero.title_part2': 'No Redirection.',
    'hero.title_part3': 'Sell directly inside the DNS.',
    'hero.desc': 'The IETF standard RFC 10023 defines how domain sale offers are published directly within the Domain Name System. Instead of redirecting visitors to parked advertising pages, owners place price and contact information in a TXT record. Registrars and buyers query the offer automatically.',
    'hero.cta_validate': 'Check domain live',
    'hero.cta_generate': 'Generate record',
    'hero.cta_bulk': 'Bulk Scan →',
    'hero.stat_commission': 'Commission',
    'hero.stat_record': 'Record Type',
    'hero.stat_mandatory': 'Required Tag',

    // Terminal Hero Preview
    'hero.terminal_header': 'RFC 10023 Wire Protocol',
    'hero.terminal_comment': '# Querying domain sale data directly via DNS:',
    'hero.terminal_node': 'DNS Node:',
    'hero.terminal_dnssec': 'DNSSEC:',
    'hero.terminal_dnssec_val': 'Signed and authenticated',
    'hero.terminal_standard': 'Standard:',
    'hero.terminal_example': 'Real-world deployment: Registry SIDN (.nl)',
    'hero.terminal_spec_link': 'Read specification →',

    // Feature Cards
    'feat.bulk_title': 'Portfolio Bulk Scanner',
    'feat.bulk_desc': 'Scan up to 30 domains simultaneously, check DNSSEC and export full results to CSV.',
    'feat.badge_title': 'Verification Badge',
    'feat.badge_desc': 'Embeddable verification badges for landing pages with instant 1-click lookup.',
    'feat.api_title': 'Public REST API',
    'feat.api_desc': 'Free, high-speed interface for developers, monitoring scripts, and automated bots.',
    'feat.legal_title': 'Legal & Regulations',
    'feat.legal_desc': 'Imprint compliance, tax handling, contract law, and price disclosure standards.',

    // Definition Box
    'def.badge': 'IETF Specification',
    'def.text': 'RFC 10023 standardizes domain sale signaling via a DNS TXT Resource Record under the authoritative node _for-sale.[domain]. The protocol enables registrars, resolvers, and automated scrapers to parse standardized sale parameters (v=FORSALE1;), asking prices (fval), and contact endpoints (furi) directly from the authoritative DNS zone.',
    'def.spec_link': 'RFC 10023 Specification →',

    // Bento / Comparison Grid
    'bento.bg_badge': 'Background',
    'bento.main_title': 'Why DNS-based signaling replaces conventional domain parking',
    'bento.card1_badge': 'Workflow',
    'bento.card1_title': 'Instant discovery during Whois and registrar availability queries',
    'bento.card1_desc': 'Previously, buyers had to visit a web browser to discover if a domain was for sale. RFC 10023 moves this discovery layer directly into DNS resolution:',
    'bento.step1': '1. Owner creates TXT record',
    'bento.step2': '2. Resolver reads v=FORSALE1',
    'bento.step3': '3. Registrar displays sale option',
    'bento.card1_footer': 'No dependency on third-party parking ad farms',
    'bento.card1_tech_link': 'Technical Details →',

    'bento.card2_badge': 'Comparison',
    'bento.card2_title': 'Traditional Parking vs. RFC 10023',
    'bento.row_commission': 'Sales Commission',
    'bento.row_commission_val': '0 % (on direct sales)',
    'bento.row_ns': 'Nameserver Switching',
    'bento.row_ns_val': 'Not required',
    'bento.row_deindex': 'Search Engine Deindexing',
    'bento.row_deindex_val': 'Zero risk',
    'bento.row_dnssec': 'DNSSEC Signatures',
    'bento.row_dnssec_val': 'Fully supported',
    'bento.row_machine': 'Machine-Readable',
    'bento.row_machine_val': 'Official IETF Standard',
    'bento.card2_note': '* Applies to direct peer-to-peer transactions initiated through the DNS contact URI.',

    'bento.card3_badge': 'Production Deployment',
    'bento.card3_title': 'Registry SIDN (.nl) checks RFC 10023 on availability lookups',
    'bento.card3_desc': 'The official .nl registry SIDN automatically queries the _for-sale TXT node during domain searches. If a .nl domain is listed for sale, the price and contact URI appear directly inside the registrar results.',
    'bento.card3_btn': 'Open SIDN.nl',

    // Quote
    'quote.text': '"RFC 10023 cleanly decouples the sale offer from the website content. A domain does not need to sit dormant or be pointed to spammy advertising banners just to signal to prospective buyers that acquisition offers are welcome."',
    'quote.author': '— IETF DNSOP Working Group',

    // FAQs
    'faq.badge': 'Frequently Asked Questions',
    'faq.title': 'Common Questions about RFC 10023',
    'faq.desc': 'Detailed answers to the most critical technical, legal, and operational questions regarding the IETF standard for domain sale signals in the DNS.',
    'faq.view_all': 'Explore all Questions in the FAQ Hub →',
    'faq.search_placeholder': 'Search FAQs...',
    'faq.cat_all': 'All Topics',
    'faq.cat_general': 'General & Purpose',
    'faq.cat_technical': 'Technical & DNSSEC',
    'faq.cat_legal': 'Legal & Taxes',
    'faq.cat_hoster': 'Hosters & Registrars',
    'faq.q1': 'Why RFC 10023 instead of classic domain parking at Sedo or Afternic?',
    'faq.a1': 'Classic parking pages carry significant disadvantages: ad blockers suppress banners, search engines penalize parked sites by deindexing them, and brokers charge 10% to 15% commissions. With RFC 10023, your domain stays on your regular nameservers or website. The sale signal is embedded right inside the DNS, accessible to registrars and buyers without intermediaries.',
    'faq.q2': 'Must each tag be placed in a separate TXT record?',
    'faq.a2': 'According to RFC 10023 Section 2.1, the IETF specification states that each TXT record should contain exactly one tag-value pair (e.g. record 1 with "v=FORSALE1;fval=USD195000" and record 2 with "v=FORSALE1;furi=https://..."). Our generator supports both this multi-line standard and a single-line fallback for limited DNS control panels.',
    'faq.q3': 'How do registrars and brokers discover that a domain is for sale?',
    'faq.a3': 'Registrars like SIDN for .nl perform a DNS query for Type 16 (TXT) at the node name _for-sale during domain availability checks. When the resolver finds "v=FORSALE1", the registrar immediately presents the asking price and contact URI to the buyer.',
    'faq.q4': 'What are the costs of using this DNS standard?',
    'faq.a4': 'Zero. RFC 10023 is an open IETF standard. Adding TXT records to your DNS zone is a standard, free feature included with virtually every domain registrar worldwide.',
    'faq.q5': 'How do domain owners protect themselves from email spam?',
    'faq.a5': 'In the furi tag, we strongly recommend pointing to a protected contact form, a project landing page, or an escrow service (e.g. Escrow.com) rather than exposing a plain mailto: address. This preserves full machine-readability while blocking spam harvesters.',
    'faq.q6': 'What is the purpose of the mandatory v=FORSALE1 tag?',
    'faq.a6': 'v=FORSALE1 is the standardized protocol and version header specified by RFC 10023. It must appear at the start of every RFC 10023 TXT record followed by a semicolon. Without this tag, automated parsers and registrars will ignore and discard the record.',
    'faq.q7': 'Which currency and pricing formats are supported in fval?',
    'faq.a7': 'The fval tag strictly requires the 3-letter ISO 4217 currency code immediately prefixed to the numerical value without spaces (e.g. EUR5000 or USD12500). Decimals are separated by a period (e.g. EUR2500.50). For negotiable pricing (OBO), the fval tag is omitted and clarified in the ftxt field.',
    'faq.q8': 'How does RFC 10023 integrate with DNSSEC?',
    'faq.a8': 'RFC 10023 works seamlessly with DNSSEC. Since _for-sale is a standard node within the DNS zone, the TXT RRset is cryptographically signed by the corresponding RRSIG record. This guarantees tamper-proof validation for buyers and registrars against DNS spoofing and cache poisoning attacks.',
    'faq.q9': 'What Time-to-Live (TTL) should be configured for the TXT record?',
    'faq.a9': 'We recommend a standard TTL of 3600 seconds (1 hour) or 7200 seconds. If pricing changes or the domain is sold, removing or altering the record propagates through global resolver caches within one to two hours.',
    'faq.q10': 'Is a DNS sale record a legally binding offer to contract?',
    'faq.a10': 'No. Under international civil and contract law, publishing an asking price in a DNS record constitutes an invitation to treat (invitatio ad offerendum). Domain owners retain full contractual liberty to accept or reject incoming acquisition bids.',
    'faq.q11': 'Do legal imprint and disclosure laws apply to the DNS record?',
    'faq.a11': 'A DNS TXT record itself is not a telemedia service and cannot house a complete imprint due to byte limits. However, the contact URI specified in furi must lead to a site containing complete imprint and privacy disclosure notices.',
    'faq.q12': 'What if my registrar or DNS control panel forbids underscores in hostnames?',
    'faq.a12': 'Some legacy web panels mistakenly validate DNS leaf nodes against archaic hostname syntax (RFC 1123). In such cases, you can delegate nameservers free of charge to modern DNS providers like Cloudflare, Hetzner DNS, or deSEC while retaining your domain registration.',
    'faq.q13': 'Is there a character or byte limit for the TXT record?',
    'faq.a13': 'Yes. Under RFC 1035, a single character-string within a DNS TXT record cannot exceed 255 bytes. Our generator incorporates a real-time Byte-Guard counter to ensure your strings never exceed wire-format limits.',
    'faq.q14': 'Can a domain remain live with an active website while signaling sale availability?',
    'faq.a14': 'Yes! This is one of RFC 10023’s premier advantages. Your live web application, store, or blog on www and the apex domain functions without interruption. Only the dedicated _for-sale node signals availability to prospective buyers and registrars in the background.',

    // Widget Embed
    'widget.title': 'Embeddable Webmaster Widget',
    'widget.desc': 'Integrate the RFC 10023 Validator or Generator directly into your website, tech blog, or customer portal.',
    'widget.copy_btn': 'Copy Code',
    'widget.copied': 'Copied!',

    // Validator Page standalone
    'valpage.badge': 'DNS Lookup',
    'valpage.title': 'RFC 10023 DNS Validator',
    'valpage.desc': 'Inspect domains worldwide in real time for valid _for-sale TXT records and their compliance with the IETF standard.',
    'valpage.diag_title': 'How does this check work?',
    'valpage.diag_text': 'Queries run directly from your browser to public anycast resolvers from Cloudflare and Google. The DoH client queries the TXT record at _for-sale.[domain] and validates the mandatory v=FORSALE1; tag, price (fval), contact URI (furi), and notes (ftxt).',

    // Generator Page standalone
    'genpage.badge': 'Generator',
    'genpage.title': 'RFC 10023 Generator',
    'genpage.desc': 'Create standard-compliant DNS TXT records for your domains and export copy-paste configurations for Cloudflare, BIND, Hetzner, INWX, Terraform, and CLI.',
    'genpage.guide_title': 'How to publish the record',
    'genpage.step1_title': '1. Open DNS Panel',
    'genpage.step1_desc': 'Log in to your domain registrar or DNS provider and open the DNS management zone.',
    'genpage.step2_title': '2. Select Type and Name',
    'genpage.step2_desc': 'Choose TXT as record type and set _for-sale as the host or subdomain name.',
    'genpage.step3_title': '3. Verify',
    'genpage.step3_desc': 'Paste the generated text string as value. Within minutes you can verify propagation with our validator.',

    // Validator Component
    'val.badge': 'Live DNS lookup with host inspection',
    'val.title': 'RFC 10023 Validator',
    'val.node_prefix': 'Node: _for-sale.[domain]',
    'val.placeholder': 'exampledomain.com',
    'val.invalid_domain': 'Please enter a valid domain name (e.g. forsaledns.net or exampledomain.com).',
    'val.btn_check': 'Check',
    'val.btn_checking': 'Checking...',
    'val.examples': 'Examples:',
    'val.dig_btn': 'dig command',
    'val.dig_copied': 'dig copied!',
    'val.dig_title': 'Copy matching terminal command',
    'val.esc_hint': '[Esc to clear]',
    'val.copy_record': 'Copy record',
    'val.record_copied': 'Copied!',
    'val.dnssec_confirmed': 'DNSSEC confirmed',
    'val.detected_hoster': 'Detected Nameserver',
    'val.create_for_hoster': 'Create record for this provider',
    'val.architecture_label': 'Structure:',
    'val.price_label': 'Asking Price',
    'val.price_empty': 'Not specified',
    'val.contact_label': 'Contact URI',
    'val.contact_empty': 'No URI specified',
    'val.note_label': 'Note / Remarks',
    'val.warnings_title': 'Record Warnings & Notes:',
    'val.raw_show': '[+] Show Raw TXT',
    'val.raw_hide': '[-] Hide Raw TXT',
    'val.raw_title': 'Raw DNS TXT Answers',
    'val.inspector_show': '[+] DNS Inspector',
    'val.inspector_hide': '[-] Hide DNS Inspector',
    'val.dnssec_valid': 'true (validated)',
    'val.dnssec_unsigned': 'false (unsigned)',
    'val.seconds': 'seconds',
    'val.share_title': 'Share test result for',
    'val.share_end': ':',
    'val.audit_title': 'Domain Audit & Email Security',
    'val.audit_badge': 'Multi-Vector DNS Assessment',
    'val.audit_score_label': 'Readiness Index',
    'val.audit_copy_json': 'Copy JSON',
    'val.audit_json_copied': 'JSON Copied!',
    'val.audit_share_link': 'Copy Link',
    'val.audit_link_copied': 'Link Copied!',
    'val.audit_email_hygiene': 'Email & Routing Protection',
    'val.audit_tab_all': 'All Checks',

    // Search Component
    'search.button_label': 'Search',
    'search.shortcut': '⌘K',
    'search.placeholder': 'Search tools, tags (fval, furi), hosters...',

    // Generator Component
    'gen.badge': 'Create DNS record',
    'gen.title': 'RFC 10023 Generator',
    'gen.rfc_conform': 'RFC 10023 compliant',
    'gen.step1': '1. Domain Name',
    'gen.step2': '2. Asking Price (fval)',
    'gen.vhb': 'Negotiable (OBO)',
    'gen.step3': '3. Contact Address or URI (furi)',
    'gen.step3_hint': 'Recommendation: Link to an escrow provider (e.g. Escrow.com), Sedo, Afternic, or a protected contact form.',
    'gen.step4': '4. Note or Remarks (ftxt)',
    'gen.format': 'Format:',
    'gen.format_multi': 'Multi-Record RRset (IETF RFC 10023 Standard)',
    'gen.format_single': 'Single-Line (Workaround)',
    'gen.format_single_warn': 'Specification Notice: According to RFC 10023 Section 2.1, each TXT record MUST NOT contain more than one tag-value pair. Use this single-line mode exclusively as a legacy workaround if your DNS provider interface prohibits multiple TXT records on the same node name.',
    'gen.copy_code': 'Copy Code',
    'gen.copied': 'Copied!',
    'gen.share_link': 'Share Link',
    'gen.node_label': 'Node: _for-sale.',
    'gen.vhb_note': 'Standard logic: When negotiable (OBO), no fval tag is set; the notice is placed in the ftxt field.',
    'gen.default_domain': 'exampledomain.com',
    'gen.default_ftxt': 'Incl. escrow service, immediate transfer',
    'gen.vhb_tag': 'Negotiable (OBO)',
    'gen.furi_placeholder': 'https://escrow.com/... or https://your-site.com/contact',
    'gen.ftxt_placeholder': 'Includes escrow transaction and VAT invoice',
    'gen.size_label': 'Size:',
    'gen.size_rfc': 'Bytes (RFC 1035 compliant)',
    'gen.share_label': 'Audit link:',
    'gen.tab_zonefile': 'Zonefile',
    'gen.tab_cf': 'Cloudflare',
    'gen.tab_hetzner': 'Hetzner',
    'gen.tab_inwx': 'INWX',
    'gen.tab_tf': 'Terraform',
    'gen.tab_dnscontrol': 'DNSControl',
    'gen.tab_cli': 'dig / curl',
    'gen.byte_warn_title': 'Warning: String too long',
    'gen.byte_warn_text': 'A single DNS TXT character string cannot exceed 255 bytes. Please shorten the note (ftxt) or contact URI (furi).',
    'gen.comment_bind_zone': '; DNS records for zonefile:',
    'gen.comment_bind_node': '; Node: _for-sale.',
    'gen.comment_bind_type': '(Type TXT, IN class)',
    'gen.comment_cf_dash': '# Cloudflare DNS Dashboard (create records individually):',
    'gen.comment_cf_hint': '# Note: Enter content without quotes in the dashboard.',
    'gen.entry_label': 'Record',
    'gen.type_label': 'Type',
    'gen.name_label': 'Name',
    'gen.content_label': 'Content',
    'gen.value_label': 'Value',
    'gen.comment_hetzner_dash': '# Hetzner DNS Console (dns.hetzner.com):',
    'gen.comment_hetzner_hint': '# Enter name as \'_for-sale\':',
    'gen.comment_inwx_dash': '# INWX or Netcup DNS Manager:',
    'gen.comment_tf_def': '# Terraform Definition (Cloudflare Provider)',
    'gen.comment_cli_dig': '# 1. Local lookup with dig:',
    'gen.comment_cli_doh': '# 2. DNS over HTTPS query (Cloudflare):',
    'gen.comment_cli_api': '# 3. Direct query via rfc10023.de API:',

    // E-E-A-T Trust Box
    'trust.badge': 'E-E-A-T Editorial Board & Sources',
    'trust.title': 'Editorial Quality Standard & Primary Sources',
    'trust.reviewed_by': 'Technical Editorial Board rfc10023.de · Updated: September 2026',
    'trust.standards_label': 'Audited against Standards:',
    'trust.standards_val': 'IETF RFC 10023 · RFC 1035 · RFC 8552 · W3C DoH (RFC 8484)',
    'trust.sources_label': 'Official Primary Sources:',
    'trust.sources_val': 'IETF Datatracker, RFC Editor, SIDN (nl), DENIC eG, Cloudflare & Google Public DNS.',
    'trust.methodology': 'Methodology & Transparency: All lookups execute in real time without caching via DNS over HTTPS (DoH) against authoritative anycast resolvers. All record builders enforce wire-format length constraints (max. 255 bytes per character-string per RFC 1035).',

    // Footer Links
    'footer.claim': 'The independent reference portal and developer toolkit for the IETF standard RFC 10023. Decentralized, standardized signaling of domain sale intentions without proprietary platform lock-in.',
    'footer.disclaimer_title': 'Independence Notice:',
    'footer.disclaimer': 'rfc10023.de is an independent educational and technical portal. There is no corporate affiliation with the Internet Engineering Task Force (IETF) or DENIC eG.',
    'footer.tools_title': 'Tools & Hub',
    'footer.link_validator': 'Live DNS Validator',
    'footer.link_generator': 'Record Builder & Byte Guard',
    'footer.link_bulk': 'Portfolio Bulk Scanner',
    'footer.link_badge': 'Trust Badge Generator',
    'footer.link_api': 'Public REST API',
    'footer.link_matrix': 'DNS Providers',
    'footer.standards_title': 'Standards & Legal',
    'footer.link_legal': 'Legal & Taxes Guide',
    'footer.link_spec': 'IETF Specification Guide',
    'footer.link_faq': 'Frequently Asked Questions (FAQ)',
    'footer.link_orig_rfc': 'IETF RFC 10023 Original',
    'footer.link_imprint': '→ Imprint / Legal Notice',
    'footer.link_privacy': 'Privacy Policy (GDPR)',
    'footer.share_label': 'Share this portal:',
    'footer.status_info': 'IETF RFC 10023 · Status: Informational · Published: Sept. 2026',
    'footer.gdpr': '100% GDPR Compliant',
    'footer.analytics': 'Cookieless Vercel Analytics',
    'footer.imprint_bottom': 'Imprint',

    // Matrix Page & HosterMatrix
    'matrix.badge': 'DACH Provider Evaluation',
    'matrix.title': 'DNS Providers & Hosters Compatibility Matrix',
    'matrix.desc': 'Which DNS hoster supports underscore labels like _for-sale in their web interface? Detailed test results for Hetzner, Cloudflare, INWX, Netcup, Strato, IONOS and more.',
    'matrix.subbadge': 'Compatibility Matrix DACH',
    'matrix.subtitle': 'DNS Zone Editors & Providers RFC 10023 Benchmark',
    'matrix.search_placeholder': 'Search provider...',
    'matrix.filter_all': 'All Statuses',
    'matrix.filter_supported': '🟢 Fully Supported',
    'matrix.filter_partial': '🟡 Partial / Workaround',
    'matrix.col_provider': 'Provider / Service',
    'matrix.col_origin': 'Region',
    'matrix.col_status': 'RFC 10023 Status',
    'matrix.col_syntax': 'Zone Editor Syntax',
    'matrix.col_notes': 'Notes & Practical Workaround',
    'matrix.status_supported': 'Fully Supported',
    'matrix.status_partial': 'Partial Support',
    'matrix.tech_bg_title': 'Technical Background: Why do some hosters reject underscores?',
    'matrix.tech_bg_text': 'Historically, the standard for hostnames (RFC 1035 / RFC 1123) only permitted characters [a-z0-9-]. However, the Domain Name System protocol itself allows arbitrary octets under RFC 2181. For service records and global attributes, the IETF formalized underscored leaf nodes in RFC 8552 (such as _dmarc, _domainkey, and now _for-sale). Modern DNS providers support this fully; older control panels still erroneously validate input against strict hostname syntax.',
    'matrix.rec_title': 'Recommended DNS Providers',
    'matrix.rec_text': 'For managing portfolios and utilizing RFC 10023 flexibly, choose providers with modern DNS engines: Cloudflare DNS, Hetzner DNS Console, INWX, or deSEC. Records can be created without validation errors and propagate globally within seconds.',
    'matrix.workaround_title': 'Workaround for Restrictive Hosters',
    'matrix.workaround_text': 'If your hoster’s web control panel (such as legacy Strato or IONOS tiers) rejects underscore characters, you can delegate your domain’s authoritative nameservers to Cloudflare or deSEC free of charge. Your domain registration remains unchanged with your existing registrar.',
    'matrix.citation_title': 'DNS Providers & Hosters Compatibility Matrix for RFC 10023',

    // Bulk Page & BulkValidator
    'bulk.badge': 'Portfolio Tool',
    'bulk.title': 'Portfolio Bulk Scanner for RFC 10023',
    'bulk.desc': 'Scan up to 30 domains simultaneously for existing _for-sale records, DNSSEC validation, and authoritative nameservers. Essential for domain investors, registrars, and brokers.',
    'bulk.subbadge': 'Multi-Domain Portfolio Auditor',
    'bulk.limit_badge': 'Up to 30 domains in parallel',
    'bulk.label_input': 'Enter domains (One domain per line):',
    'bulk.placeholder': 'domain1.com\ndomain2.net\ndomain3.org',
    'bulk.btn_start': 'Start Bulk Scan',
    'bulk.btn_scanning': 'Scanning Portfolio',
    'bulk.btn_export': 'Export Results to CSV',
    'bulk.col_domain': 'Domain',
    'bulk.col_status': 'Status',
    'bulk.col_price': 'Price (fval)',
    'bulk.col_contact': 'Contact (furi)',
    'bulk.col_hoster': 'Provider',
    'bulk.col_dnssec': 'DNSSEC',
    'bulk.status_valid': 'Valid',
    'bulk.status_syntax': 'Syntax',
    'bulk.status_not_found': 'No Record',
    'bulk.status_pending': 'Querying...',
    'bulk.status_error': 'Error',
    'bulk.dnssec_yes': 'YES',
    'bulk.dnssec_no': 'No',
    'bulk.privacy_title': 'Operation & Privacy Notice:',
    'bulk.privacy_text1': 'Queries execute directly in your browser using DNS over HTTPS (DoH). We do not store or track any of your domain lists on our servers.',
    'bulk.privacy_legal': 'Legal Notice: This evaluation is for informational purposes only. A discovered DNS record does not constitute a binding legal contract, but merely signals the owner’s willingness to sell.',

    // Badge Page & BadgeGenerator
    'badge.badge': 'Domain Verification',
    'badge.title': 'Badge Generator for RFC 10023',
    'badge.desc': 'Build trust with prospective buyers: Embed a verifiable badge on your landing pages or portfolio site. Buyers can verify the DNS record independently with a single click.',
    'badge.subbadge': 'Verification Seal for Websites & Portfolios',
    'badge.verified_pill': '✓ DNS Verified',
    'badge.domain_label': 'Domain Name',
    'badge.theme_label': 'Color Theme',
    'badge.theme_dark': 'Dark (Slate)',
    'badge.theme_emerald': 'Green (Emerald)',
    'badge.theme_light': 'Light (White)',
    'badge.show_price': 'Show Price',
    'badge.show_price_box': 'Include price in badge',
    'badge.price_label': 'Price or Notice',
    'badge.preview_label': 'Preview (Clickable verification link):',
    'badge.preview_text': 'Buyers click directly to the independent verification result on rfc10023.de confirming the authoritative DNS record.',
    'badge.code_web_title': 'Code for Websites and Landing Pages',
    'badge.code_md_title': 'Markdown for GitHub or Readme',
    'badge.copy_html': 'Copy HTML',
    'badge.copy_md': 'Copy Markdown',
    'badge.benefit1_title': 'Proof of Ownership',
    'badge.benefit1_desc': 'Prospective buyers see immediately that the sale offer originates directly from the authoritative DNS zone.',
    'badge.benefit2_title': 'Zero Commissions',
    'badge.benefit2_desc': 'Link directly to your own contact form or an escrow service like Escrow.com and save 10-15% broker fees.',
    'badge.benefit3_title': 'Privacy-Friendly',
    'badge.benefit3_desc': 'The badge code requires zero external trackers, cookies, or remote fonts. Pure clean HTML and CSS.',

    // API Docs Page
    'api.badge': 'REST API Documentation',
    'api.title': 'Free Public API for RFC 10023',
    'api.desc': 'For developers, registrars, and automated bots: Query any domain through our DNS infrastructure and receive a structured JSON response with parsed tags, nameservers, and DNSSEC status.',
    'api.feature_cors': 'CORS Enabled',
    'api.feature_auth': 'No Registration Required',
    'api.feature_anycast': 'Anycast DNS',
    'api.params_title': 'Query Parameters',
    'api.col_param': 'Parameter',
    'api.col_type': 'Type',
    'api.col_required': 'Required',
    'api.col_desc': 'Description',
    'api.param_or': 'or',
    'api.param_yes': 'Yes',
    'api.param_desc': 'The domain name to inspect (e.g. exampledomain.com).',
    'api.console_title': 'Try it directly in your browser',
    'api.btn_send': 'Send Query',
    'api.btn_loading': 'Loading data...',
    'api.btn_copy_curl': 'Copy cURL',
    'api.response_label': '// Server Response (JSON):',
    'api.example_js': 'JavaScript / TypeScript Example',
    'api.example_py': 'Python Example',

    // Legal Guide Page
    'legal.badge': 'Legal Framework • International & DACH',
    'legal.title': 'Legal Guidelines for DNS-Based Domain Sales (RFC 10023)',
    'legal.desc': 'What domain owners and companies should know when publishing sale offers and asking prices via DNS records. Guidance on legal disclosure requirements, contract law, taxation, and trademark considerations.',
    'legal.disclaimer_title': 'Important Notice:',
    'legal.disclaimer_text': 'This overview is provided for informational and technical purposes only. It does not constitute legal or tax advice and does not replace consultation with a qualified attorney or tax professional.',
    'legal.c1_title': 'Is a DNS record a legally binding offer to sell?',
    'legal.c1_text1': 'No. Under civil law in Europe and international jurisprudence, publishing an asking price in a DNS record (such as fval=EUR2500) is not a binding public offer, but an invitation to treat (invitatio ad offerendum).',
    'legal.c1_box_title': 'Practical Implication:',
    'legal.c1_box_text': 'A buyer cannot force a contract simply by declaring acceptance. As the domain owner, you retain full contractual freedom to decide to whom and at what price you agree to sell.',
    'legal.c2_title': 'Do legal imprint and disclosure obligations apply to DNS records?',
    'legal.c2_text1': 'A DNS TXT record is not an interactive telemedia service requiring a standalone imprint. DNS character length limits also make this technically impossible.',
    'legal.c2_box_title': 'Recommendation for the furi Tag:',
    'legal.c2_box_text': 'Point your furi tag to a secure landing page, company website, or licensed escrow service containing full legal notice and privacy information to minimize unfair competition liability risks.',
    'legal.c3_title': 'VAT, Sales Tax, and Price Disclosure Regulations',
    'legal.c3_text1': 'When addressing consumers, price indication regulations generally require disclosing final prices including applicable sales tax / VAT.',
    'legal.c3_b2b': 'In B2B Transactions: Commercial sales between business entities typically quote net prices.',
    'legal.c3_rec': 'Recommendation for RFC 10023: Use the ftxt freeform tag for clarity, e.g. ftxt=Net excl. VAT / B2B transaction or ftxt=All taxes included.',
    'legal.c4_title': 'Trademark Law and Brand Protection',
    'legal.c4_text1': 'A public sale record in the DNS explicitly proves commercial intent. If a domain infringes on third-party trademarks or brand names, an inflated asking price can be viewed as evidence of bad faith in UDRP disputes or litigation.',
    'legal.c4_box': 'Important: Only use RFC 10023 for domains where you possess legitimate rights and do not infringe on third-party intellectual property.',
    'legal.cta_title': 'Build a Standard-Compliant Record',
    'legal.cta_desc': 'Use our generator featuring automatic character limit validation and copy-ready syntax exports.',
    'legal.cta_btn': 'Open Generator →',

    // Specification Page
    'spec.badge': 'IETF RFC 10023 · Status: Informational',
    'spec.title': 'RFC 10023 Specification',
    'spec.desc': 'Technical analysis and comprehensive reference for the IETF standard "The \'_for-sale\' Underscored and Globally Scoped DNS Node Name" (July 2026).',
    'spec.cat': 'Category: Informational',
    'spec.orig_link': 'IETF Original Text',
    'spec.s1_title': '1. Motivation & Discovery Architecture',
    'spec.s1_text1': 'In the secondary domain market, discovering domains available for acquisition has historically been fragmented. Buyers must navigate browser popups, parked ad pages, heavily redacted Whois directories, or isolated marketplace silos.',
    'spec.s1_text2': 'RFC 10023 introduces a decentralized, protocol-native discovery layer within the Domain Name System. Domain owners need not alter nameservers or pay parking fees: a simple DNS TXT record announces sale availability across the global internet infrastructure.',
    'spec.s2_title': '2. The Reserved DNS Node (_for-sale)',
    'spec.s2_text': 'Following RFC 8552 (Scoped, Underscored DNS Node Names), the specification adopts the _for-sale prefix. The underscore eliminates collisions with conventional hostnames (such as mail.example.com or www.example.com), which under RFC 1035 cannot contain underscores.',
    'spec.s2_comment': '; Syntax per RFC 10023 Section 2.1 (Multi-Record RRset):',
    'spec.s3_title': '3. Tag-Value Specification (Section 2.1 & 2.2)',
    'spec.s3_text': 'Under RFC 10023 Section 2.1, each TXT record must contain exactly one tag-value pair and begin with v=FORSALE1;. Multiple parameters are represented across separate records within the same Resource Record Set (RRset).',
    'spec.th_tag': 'Tag',
    'spec.th_required': 'Required',
    'spec.th_meaning': 'Meaning',
    'spec.th_example': 'Example Value',
    'spec.tag_v_desc': 'Version indicator. Must be exactly FORSALE1.',
    'spec.tag_fval_desc': 'Fixed asking price per ISO 4217 currency code immediately preceding amount. Omitted for negotiable (OBO).',
    'spec.tag_furi_desc': 'Contact URI (HTTP, HTTPS, mailto or tel conforming to RFC 3986).',
    'spec.tag_ftxt_desc': 'Human-readable description (e.g. negotiation terms, conditions).',
    'spec.tag_fcod_desc': 'Machine transaction or verification tracking code.',
    'spec.s4_title': '4. Production Deployment: The SIDN Case Study (.nl)',
    'spec.s4_text': 'The Dutch ccTLD registry SIDN (.nl) became the world’s first top-level registry to integrate RFC 10023 into its authoritative infrastructure. When a user queries domain availability on SIDN’s portal or Whois lookup, SIDN automatically checks for the _for-sale record. If present, the registrar immediately displays sale availability, price, and seller contact information.',
    'spec.s5_title': 'Security Considerations (Section 4)',
    'spec.s5_text': 'RFC 10023 does not define a native cryptographic settlement layer. Buyers should verify that the domain is signed with DNSSEC to prevent cache poisoning attacks, and are strongly encouraged to conclude transactions via licensed escrow services.',
    'spec.citation_title': 'IETF RFC 10023: The _for-sale Underscored DNS Node Name',

    // Citation Box
    'citation.title': 'Citation Reference for Publications & Media',
    'citation.default_title': 'RFC 10023: The IETF Standard for Domain Sale Signals in the DNS',
    'citation.val_title': 'RFC 10023 DNS Live Validator & Inspector',
    'citation.gen_title': 'RFC 10023 Record Generator & Multi-Format Exporter',
    'citation.copy': 'Copy Citation',
    'citation.copied': 'Citation Copied',
    'citation.status': 'Published: September 2026 · IETF Standards Track',
  }
};

const LanguageContext = createContext<LanguageContextType>({
  language: 'de',
  setLanguage: () => {},
  t: (key: string) => key,
  isSearchOpen: false,
  setIsSearchOpen: () => {},
});

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    // Initial check from current window URL
    if (typeof window !== 'undefined') {
      const pathname = window.location.pathname;
      if (pathname === '/en' || pathname.startsWith('/en/')) {
        return 'en';
      }
    }
    try {
      const saved = localStorage.getItem('rfc10023_lang');
      if (saved === 'de' || saved === 'en') return saved;
      const browserLang = navigator.language || (navigator as any).userLanguage || '';
      if (browserLang.startsWith('en')) return 'en';
      if (!browserLang.startsWith('de')) return 'en';
    } catch {}
    return 'de';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    try {
      localStorage.setItem('rfc10023_lang', lang);
      document.documentElement.lang = lang;
    } catch {}
  };

  useEffect(() => {
    document.documentElement.lang = language;
    const isEn = language === 'en';
    const canonicalLink = document.querySelector('link[rel="canonical"]');
    const ogUrl = document.querySelector('meta[property="og:url"]');
    const ogLocale = document.querySelector('meta[property="og:locale"]');
    const twitterUrl = document.querySelector('meta[name="twitter:url"]');

    if (isEn) {
      document.title = 'RFC 10023 | The IETF Standard for Domain Sale Signals in the DNS';
      const metaDesc = document.querySelector('meta[name="description"]');
      if (metaDesc) {
        metaDesc.setAttribute('content', 'Independent reference portal & developer toolkit for RFC 10023. Live DNS validator for _for-sale TXT records, builder & DNS provider matrix.');
      }
      if (canonicalLink) canonicalLink.setAttribute('href', 'https://www.rfc10023.de/en');
      if (ogUrl) ogUrl.setAttribute('content', 'https://www.rfc10023.de/en');
      if (ogLocale) ogLocale.setAttribute('content', 'en_US');
      if (twitterUrl) twitterUrl.setAttribute('content', 'https://www.rfc10023.de/en');
    } else {
      document.title = 'RFC 10023 | Der IETF-Standard für Domain-Verkaufssignale im DNS';
      const metaDesc = document.querySelector('meta[name="description"]');
      if (metaDesc) {
        metaDesc.setAttribute('content', 'Unabhängiges DACH-Referenzportal für RFC 10023. Live DNS-Validator für _for-sale TXT-Records, interaktiver Record-Generator & Hoster-Kompatibilitätsmatrix.');
      }
      if (canonicalLink) canonicalLink.setAttribute('href', 'https://www.rfc10023.de/');
      if (ogUrl) ogUrl.setAttribute('content', 'https://www.rfc10023.de/');
      if (ogLocale) ogLocale.setAttribute('content', 'de_DE');
      if (twitterUrl) twitterUrl.setAttribute('content', 'https://www.rfc10023.de/');
    }
  }, [language]);

  const [isSearchOpen, setIsSearchOpen] = useState(false);

  // Global Cmd+K / Ctrl+K shortcut listener
  useEffect(() => {
    const handleGlobalKeyDown = (e: KeyboardEvent) => {
      if ((e.metaKey || e.ctrlKey) && e.key.toLowerCase() === 'k') {
        e.preventDefault();
        setIsSearchOpen((prev) => !prev);
      }
    };
    window.addEventListener('keydown', handleGlobalKeyDown);
    return () => window.removeEventListener('keydown', handleGlobalKeyDown);
  }, []);

  const t = (key: string): string => {
    return translations[language]?.[key] || translations.de[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isSearchOpen, setIsSearchOpen }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);

